---
- name: (Redhat) Install necessary packages
  ansible.builtin.dnf:
    name:
      - yum-utils
    state: present
    update_cache: true

- name: (Redhat) Add Docker repository
  ansible.builtin.shell:
    cmd: >
      yum-config-manager --add-repo https://download.docker.com/linux/rhel/docker-ce.repo

- name: (Redhat) Install Docker Engine
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      # - python3-docker
      # - python3-jsondiff
      # - python3-pyyaml
    state: latest
    update_cache: true

- name: (Redhat) Start and enable Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
